### ISSUE TITLE
SQL error with created field

### ISSUE THREAD

**Issue by micker** [ChristopheSeg/mod_fceventscalendar#1]
if we use created field we have this error
Champ 'i.2' inconnu dans where clause SQL=SELECT i.id, i.title, i.alias, i.catid, c.alias AS category_alias ,i.created as day FROM #__content AS i JOIN #__flexicontent_items_ext AS ie ON ie.item_id = i.id JOIN #__flexicontent_types AS ty ON ie.type_id = ty.id JOIN #__flexicontent_cats_item_relations AS rel ON rel.itemid = i.id JOIN #__categories AS c ON c.id = i.catid LEFT JOIN #__users AS u ON u.id = i.created_by WHERE 1 AND rel.catid IN (8) AND ( i.state =1 ) AND ( ( i.publish_up = '0000-00-00 00:00:00' OR i.publish_up <= UTC_TIMESTAMP() ) ) AND ( ( i.publish_down = '0000-00-00 00:00:00' OR i.publish_down >= UTC_TIMESTAMP() ) ) AND ( ie.language LIKE 'fr%' OR ie.language="*" ) AND ty.access IN (0,1,1,5) AND c.access IN (0,1,1,5) AND i.access IN (0,1,1,5) AND ('2016-09-01 00:00:00'<=i.2) AND (i.2<='2016-10-01 00:00:00') ORDER BY i.title

**Comment by ChristopheSeg** [comment]
Fixed: missing one case not accounted for event filtering
